// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoListApp.Dal;

#nullable disable

namespace ToDoListApp.Dal.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20250308120955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoListApp.Dal.Models.TaskDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TaskStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            TaskStatusId = 1L,
                            Text = "Задача 1"
                        },
                        new
                        {
                            Id = 2L,
                            TaskStatusId = 2L,
                            Text = "Задача 2"
                        },
                        new
                        {
                            Id = 3L,
                            TaskStatusId = 3L,
                            Text = "Задача 3"
                        });
                });

            modelBuilder.Entity("ToDoListApp.Dal.Models.TaskStatusDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("TaskStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            TaskStatusName = "Новая"
                        },
                        new
                        {
                            Id = 2L,
                            TaskStatusName = "В процессе"
                        },
                        new
                        {
                            Id = 3L,
                            TaskStatusName = "Выполнено"
                        });
                });

            modelBuilder.Entity("ToDoListApp.Dal.Models.TaskDb", b =>
                {
                    b.HasOne("ToDoListApp.Dal.Models.TaskStatusDb", "TaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("ToDoListApp.Dal.Models.TaskStatusDb", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
